### PR TITLE
Created info notification for connecting to Godwoken_testnet

### PR DESCRIPTION
**Pull request by Pycomet**

### CODE REVIEW

**Comment by dezzyboy** [comment]
@Pycomet please make sure main is merged into your branch first prior to creating pr to merge into main. always make sure your branch is up to date with main before making any changes to avoid  conflicts  closing this as it fails to build

**Comment by Pycomet** [comment]
I am checking and rebase to main again to push

**Comment by dezzyboy** [comment]
looks like is using `yarn  build`  instead of `npm build`  will add you to vercel project to make things easier to investigate moving forward

**Comment by dezzyboy** [comment]
closing this as it fails to build repeatedly  try building it locally prior to creating a new pr thanks @Pycomet

**Pull request closed without merging**
